@baseURL = http://localhost:3000

###

GET {{baseURL}}/orders

###

POST {{baseURL}}/orders
Content-Type: application/json

{
    "date": "2022-10-13",
    "cabin": "Rasmus cabin",
    "servicetype": "Cleaning"
}

###

PATCH {{baseURL}}/orders/1
Content-Type: application/json

{
    "date": "Chimney cleaning",
    "cabin": "Stobes stuga",
    "servicetype": 30
}

###

DELETE {{baseURL}}/orders/6
