@baseURL = http://localhost:3030

###

GET {{baseURL}}/services

###

POST {{baseURL}}/services
Content-Type: application/json

{
    "servicetype": "Cleaning",
    "price": 40
}

###

PATCH {{baseURL}}/services/4
Content-Type: application/json

{
    "servicetype": "Chimney cleaning",
    "price": 30
}

###

DELETE {{baseURL}}/services/7
