@baseURL = http://localhost:3000

###

GET {{baseURL}}/services

###

POST {{baseURL}}/services
Content-Type: application/json

{
    "servicetype": "Food delivery2",
    "price": 30
}

###

PATCH {{baseURL}}/services/1
Content-Type: application/json

{
    "servicetype": "Chimney cleaning",
    "price": 30
}

###

DELETE {{baseURL}}/services/4
